### ISSUE TITLE
Ability to exclude <lastmod>

### ISSUE THREAD

**Issue by csantos42** [feross/express-sitemap-xml#12]
I'm generating a sitemap without specifying a `lastMod` intentionally since that property is optional, but the library is adding it regardless. Can we add an option to not include  `<lastmod>` unless explicitly set?

**Comment by feross** [comment]
Fixed in 3.0.0.

If you're not specifying a `url.lastMod` option, then when sitemap.xml is produced, we no longer automatically include today's date.

So this:

```
<url>
  <loc>https://bitmidi.com/3</loc>
  <lastmod>2020-11-22</lastmod>
</url>
```

Becomes this:

```
<url>
  <loc>https://bitmidi.com/3</loc>
</url>
```

If you want the old behavior, then use a url object like this:

```js
{
  url: '/3',
  lastMod: true
}
```
