### ISSUE TITLE
No trailing slash for index URL

### ISSUE THREAD

**Issue by nprail** [feross/express-sitemap-xml#9]
If I try to add an index URL to my sitemap, it always comes out in the sitemap with a trailing slash, which is not the canonical URL. 

For example, if I give it a URL which is just an empty string, it returns one with a trailing slash:
```javascript
const { buildSitemaps } = require('express-sitemap-xml')

const urls = ['']

async function run () {
  const sitemaps = await buildSitemaps(urls, 'https://event1.io')

  console.log(sitemaps['/sitemap.xml'])
  // `<?xml version="1.0" encoding="utf-8"?>
  //  <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  //    <url>
  //      <loc>https://event1.io/</loc>
  //      <lastmod>${getTodayStr()}</lastmod>
  //    </url>
  //  </urlset>`
}
```

I would expect it to look like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://event1.io</loc>
    <lastmod>${getTodayStr()}</lastmod>
  </url>
</urlset>`
```
It looks as if this is due to the fact that the `toAbsolute` function creates a new `URL` object and returns the `href` which always adds a trailing slash for the index URL.

**Comment by feross** [comment]
I don't believe this is necessary. These URLs are identical and won't be considered different by search engines or browsers. See: https://webmasters.stackexchange.com/a/33074
